apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: meine-app
data:
  config.js: |
    module.exports = {
      port: 3000,
      database: {
        host: 'mysql',
        port: 3306,
        database: 'notizapp',
        user: 'notizuser'
      }
    };