apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notiz-api-hpa
  namespace: meine-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notiz-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70